version: "1.0"
info:
  model: int-scaffold
packages:
- name: SerengetiGH1812Project
  gitServerName: srcGithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: ArtiKhareIBM
  gitBranch: main
services:
- serviceName: project.serengetigh1812.integrations:gcd
  packages:
  - name: SerengetiGH1812Project
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.2070
